### ISSUE TITLE
Crash when double-clicking on Chrome 76+

### ISSUE THREAD

**Issue by bahumbert** [xiaody/react-lines-ellipsis#61] opened 2019-09-18 09:01 UTC
Hello ! 
I've come across an interesting bug using this library: when double-clicking outside of text on the last line, apparently Chrome simply crashes (the current tab).

That's happening on Chrome 76 and 77, I tried on Windows & Mac. I couldn't reproduce this on Firefox, Edge, Safari or Chrome 75 🤔.

You can try it there:
https://codesandbox.io/s/quirky-river-86m1v (try double-clicking on the "blank" near "multine text")

**Comment by xiaody** [comment] 2019-09-18 15:11
Interesting. I can reproduce on Chrome 77 on MacOS. (Though I need to change the width from 100 to 120, maybe because we have different system font settings.)

I manage to make a minimal reproduce case, which is pure simple HTML and has nothing to do with this component or any JavaScript https://jsbin.com/vepawil/edit?html,output

I would say this is a Chrome bug and I have just reported it at https://crbug.com/1005225 .
Let's follow it there.

**Comment by xiaody** [comment] 2019-09-19 08:07
Chrome has just shipped a patch https://chromium.googlesource.com/chromium/src/+log/77.0.3865.75..77.0.3865.90?pretty=fuller&n=20 , you can see the `<wbr>` related commit.

I believe this is fixed in latest Chrome stable(77.0.3865.90).
So closing this issue. Thanks for sharing anyway.

**Closed by xiaody** 2019-09-19 08:07 UTC
